spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName: