spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:


alipay:
  app-id:
  private-key:
  alipay-public-key:
  server-url:
  charset:
  sign-type:
  notify-url:  https://read-back.cos.tg/api/orders/notify
  return-url:  https://tm.cos.tg/cart