spring:
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:


alipay:
  app-id:
  private-key:
  alipay-public-key:
  server-url:
  charset:
  sign-type:
  return-url:  http://t93tve.natappfree.cc/api/orders/returnUrl
  notify-url : http://t93tve.natappfree.cc/api/orders/notify